### ISSUE TITLE
Output dir

### ISSUE THREAD

**Issue by HanaO00** [ok100/homepage.py#4]
Hello, if i replace
 'output_dir': os.environ['HOME'],
by
 'output_dir': '.',

He output to the current folder ? It's how i do that ?

**Comment by ok100** [comment]
You can use this:
```python
'output_dir': os.getcwd(),
```

**Comment by HanaO00** [comment]
Thank you, i put just here : 

```
config = {
'output_dir': os.environ['HOME'],
```

Or here too : 
`config_file = args.config_file or '%s/.config/homepage/homepage.conf' % os.environ['HOME']`

'.' is not good ? He output only at current folder with '.' ?
